"""Add medical professional fields and password reset functionality

Revision ID: add_medical_professional_fields
Revises: 
Create Date: 2026-02-08 10:08:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_medical_professional_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to users table
    op.add_column('users', sa.Column('is_medical_professional', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('specialty', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('temporary_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('temporary_password_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    
    # Create unique index for license_number
    op.create_index('ix_users_license_number', 'users', ['license_number'], unique=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_users_license_number', table_name='users')
    
    # Drop columns
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'temporary_password_expires')
    op.drop_column('users', 'temporary_password')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'is_first_login')
    op.drop_column('users', 'specialty')
    op.drop_column('users', 'license_number')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_medical_professional')
    
    # ### end Alembic commands ###
